version: '3.8'

services:
  db-local:
    image: postgres:15-alpine
    container_name: mauromera_local_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mauromera_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mauromera_local"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_local:
